### ISSUE TITLE
rework tagging procedure

### ISSUE THREAD

**Issue by kreetrapper** [commul/lindat-common#2]
The way tagging/releasing currently works creates quite some headache when new changes from upstream have to be merged into our fork. We should look into a way to avoid this, by keeping our version number out of the files that track the "official" version number.

**Comment by iiegn** [comment]
For a long time I had actually forgotten that this was part of *our* deployment. After some consideration, I think, it would be easier to drop the dependency altogether: it basically gives us a header and a footer that we need to adapt quite a lot anyway... For the time being, we'll be using our latest release (which deactivated Google Analytics), and probably can stay with this for a while - hopefully, until we don't need to merge our fork with upstream any longer.
